<?xml version='1.0' encoding='UTF-8'?>
<testsuites name='NetworkKitTests.xctest' tests='9' failures='4'>
  <testsuite name='NetworkKitTests.NetworkTests' tests='9' failures='4'>
    <testcase classname='NetworkKitTests.NetworkTests' name='testBlockValidation'>
      <failure message='failed - should have a HTTP response and status code'>/Users/andre/Dev/NetworkKit/Tests/NetworkKitTests/NetworkTests.swift:122</failure>
    </testcase>
    <testcase classname='NetworkKitTests.NetworkTests' name='testCancelRequest' time='0.004'/>
    <testcase classname='NetworkKitTests.NetworkTests' name='testChainedRequests' time='1.090'/>
    <testcase classname='NetworkKitTests.NetworkTests' name='testDefaultValidation' time='0.050'/>
    <testcase classname='NetworkKitTests.NetworkTests' name='testErrorResponse'>
      <failure message='Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: &quot;should parse error model as error&quot;.'>/Users/andre/Dev/NetworkKit/Tests/NetworkKitTests/NetworkTests.swift:182</failure>
    </testcase>
    <testcase classname='NetworkKitTests.NetworkTests' name='testInvalidURL' time='0.012'/>
    <testcase classname='NetworkKitTests.NetworkTests' name='testSuccessClient'>
      <failure message='failed - shouldn&apos;t succeed'>/Users/andre/Dev/NetworkKit/Tests/NetworkKitTests/NetworkTests.swift:88</failure>
    </testcase>
    <testcase classname='NetworkKitTests.NetworkTests' name='testSuccessClient'>
      <failure message='Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: &quot;should make a sucessful get request and decode the response&quot;.'>/Users/andre/Dev/NetworkKit/Tests/NetworkKitTests/NetworkTests.swift:92</failure>
    </testcase>
    <testcase classname='NetworkKitTests.NetworkTests' name='testValidationWithValidator' time='0.008'/>
  </testsuite>
</testsuites>